### ISSUE TITLE
Ingest of MP4 fails at transcode step.

### ISSUE THREAD

**Issue by mikebuckley** [awslabs/media2cloud#1]
Trying to upload a fairly small (32MB) video using the web page.   However, the process fails with this error in the system log file:

Error=Cannot read property 'length' of undefined

Process does not continue, and pretty much hangs at this point.  Tried several different files, same results.

**Comment by aws-kens** [comment]
Hi @mikebuckley,

Any chance that you can share your MP4 file? I would like to see if I can reproduce the issue on my instance.

Ken

**Comment by mikebuckley** [comment]
Seems that GitHub doesn't like the size of my file (32MB).   If you send me an email to mike@mikebuckley.net . I will send you a link to the file on dropbox!, or perhaps S3?

**Comment by mikebuckley** [comment]
A bit more information:

This is the error message returned in email when it fails.

{
  "Error": "TranscodeError",
  "Cause": "{\"errorMessage\":\"TypeError: Cannot read property 'length' of undefined\",\"errorType\":\"TranscodeError\",\"stackTrace\":[\"exports.startTranscode (/var/task/lib/ingest/transcode/index.js:106:47)\",\"<anonymous>\",\"process._tickDomainCallback (internal/process/next_tick.js:228:7)\"]}"
}
  I hope that is a help.

**Comment by aws-kens** [comment]
Hi @mikebuckley,

Thanks for sharing the files. I was able to reproduce the issue and found that all of your files don't contain any audio. The current version of Media2Cloud requires to have both video and audio. It failed when it tried to map the audio channel.

We will try to improve it in the next release. Meanwhile, can you try to use other MP4 files that contain both audio and video?

Thanks for your understanding,
Ken

**Comment by mikebuckley** [comment]
Files with audio are loaded fine!  Closing this Issue.   Thanks again!
