### ISSUE TITLE
Image-ExifTool-11.70.tar.gz not found when running ./build-s3-dist.sh

### ISSUE THREAD

**Issue by anggras** [awslabs/media2cloud#10]
Following is the error:
```
--2021-06-23 20:13:38--  https://exiftool.org/Image-ExifTool-11.70.tar.gz
Resolving exiftool.org (exiftool.org)... 173.236.184.68
Connecting to exiftool.org (exiftool.org)|173.236.184.68|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-23 20:13:40 ERROR 404: Not Found.
```

**Comment by aws-kens** [comment]
Hi anggras,

Thanks for reporting the issue.
Just curious if you are working on the master branch or the v3preview branch?
If you have not seen the v3preview branch, I highly recommended you to use v3preview.
https://github.com/awslabs/media2cloud/tree/v3preview

The exiftool fix has been commited to v3preview branch.

Thanks.

**Comment by anggras** [comment]
Ah, nice. Will have a look at v3preview branch.

Cheers.
