### ISSUE TITLE
Rekognition Custom Face Collection

### ISSUE THREAD

**Issue by abutail** [awslabs/media2cloud#2]
Hi I uploaded a custom face in the collection externally but when when I am playing the video it is not detecting the custom face can you please advise how to get custom face information in the video?

**Comment by aws-kens** [comment]
Hi @abutail 
The current version of Media2Cloud doesn't support indexing faces. It is a feature that we are working on.

**Comment by aws-kens** [comment]
Hi @abutail,
We just published an updated version of Media2Cloud which allows you to index faces into Rekognition Face Collection. It also comes with a lot of new features. Give it a try.
