### ISSUE TITLE
About upgrading mediainfo and its related lambda layer

### ISSUE THREAD

**Issue by hmachefe** [awslabs/media2cloud#5]
Have you ever planned to upgrade https://github.com/awslabs/media2cloud/tree/master/source/layers/mediainfo (linux binary / windows DLL) and the lambda layer sources leveraging on it ?

The version of https://github.com/awslabs/media2cloud/tree/master/source/layers/mediainfo/amazon/linux2/mediainfo is currently 0.7.99 

Whereas the latest official version of https://mediaarea.net/download/binary/mediainfo/20.08/MediaInfo_CLI_20.08_Lambda.zip is 20.08

Then the (new) XML format produced from running source/layers/mediainfo/index.js would not be compliant anymore. Javascript execution of such a lambda layer will get broken as a consequence because of unexpected XML output produced by https://mediaarea.net/download/binary/mediainfo/20.08 executable.

The reason why I wonder if updating mediainfo and especially its backed-up lambda master/source/layers/mediainfo/index.js was in your roadmap or in AWSLABS plans ?

**Comment by aws-kens** [comment]
@hmachefe,
We are qualifying the latest mediainfo v20.08 and updating the nodeJS codes. Will publish an update when it passes the test.

**Comment by hmachefe** [comment]
Great, good news, your prompt and smart feedback is greatly appreciated. Any idea about when it will be published approximately ? Next month ? maybe earlier ? Just to have an estimation

**Comment by aws-kens** [comment]
Hi @hmachefe,

v20.08 unit test is looking good. I am testing the M2C state machines and web app where it uses the mediainfo. Will keep you updated when the code is ready.

Just curious if you have any AWS contact (Account Manager or Solution Architects) who works with you on this?

**Comment by hmachefe** [comment]
Excellent, sounds great. (We are impressed). OTH I am afraid we don't have any AWS contact (Account Manager or Solution Architects) who works with us on this. I first contacted AWS support team who gently redirected our original requests to you.

**Comment by aws-kens** [comment]
Hi @hmachefe,

Updated the code to use v20.08 mediainfo.
