### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by theguate** [awslabs/media2cloud#9]
I have deployed in an account where I have admin rights, all the deployment seems to complete fine, then I receive the email with the URL and the credentials, the landing page loads fine, I can see the architecture but the settings or demo page,or login / sign-in they are not loading any content. https://db2qsk3w2h2o8.cloudfront.net/

**Comment by aws-kens** [comment]
Hi @theguate ,
Does the webapp prompt you to sign in? What happens if you click on the SIGIN link on the top right corner?
I just tried the link you provided and did see the Cognito sign-in dialog.
Also try to open the link with Incognito mode in Chrome?

**Comment by theguate** [comment]
Hi, yes now I can see the Cognito sign-in dialog. It seems that takes some aditional time after the deployments shows as completed in the cloudformation to the application is fully ready. Many thanks for the reply!

**Comment by aws-kens** [comment]
Yes, this issue will be addressed in the next release. Closing the issue for now.
